### ISSUE TITLE
지역별 지출 내역 대한민국 지도 적용하기

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/wheredoesmymoneygo.kr#1]
- [ ] 축약된 svg 지도 데이터 구하기

**Comment by mozodev** [comment]
https://github.com/southkorea/southkorea-maps
??
http://bl.ocks.org/e9t/5409484
http://bl.ocks.org/e9t/5409518

**Comment by hoony-o-1** [comment]
저번에 강철님 교육 때 저도 알게되었는데 이게 쓸데없이 세밀한 바람에 용량이 너무 커서 이걸 더 줄일 수 있는 방법이나 더 축약된 버전이 없나 찾고있어요!

**Comment by jeff-lim** [comment]
이거 어때요. 포퐁 깃헙에 있는 파일에서 수정했어요. 세종시도 표기가 되어있네요(14kb)
https://github.com/jeff-lim/southkorea-maps/blob/master/popong/skorea-provinces-v3.5.svg
포퐁 깃헙에 있던 svg의 라이센스는 CC BY 3.0입니다

**Comment by mozodev** [comment]
오. 벡터 그래픽 편집도 하시나요? 
![우리나라 행정구역 지도](https://photos-1.dropbox.com/t/0/AAChGfMguA_HEXEgDE4DNK-P1jQ1qv3nqswQ6Rxwrj039g/12/55177834/png/320x320/1/_/0/4/korea-province-map.png/1jegr0db69umxbl/AABbFeNlMTHNXIusElR4bwp8a/korea-province-map.png)
ㅎㅎ 일러로 열어서 선 두께를 0.25pt로 한 저장한 이미지...

좋네요!

**Comment by hoony-o-1** [comment]
팀포퐁이 축약해놓은 파일은 이미 시도해보았는데 동작하지 않아요, 소스코드의 차이를 보면 path가 그려지는 좌표가 차이가 있는 걸 볼 수 있을거에요. 이게 어디서 발생하는 차이인지는 모르겠지만...
- 소스코드
  [https://raw.githubusercontent.com/codeforseoul/wheredoesmymoneygo.kr/gh-pages/img/korea.svg](https://raw.githubusercontent.com/codeforseoul/wheredoesmymoneygo.kr/gh-pages/img/korea.svg)

**Comment by jeff-lim** [comment]
벡터 편집이라니는 좀 부끄럽고요....ㅋㅋㅋㅋ

새벽에 공유드린 파일은 어도비 일러스터로 import해서
svg로 새로 export한 파일이에요. 혹시 좌표 표현식이 달라졌을 수도!

2014년 8월 6일 오전 10:32, Seunghun Jang notifications@github.com님이 작성:

**Comment by hoony-o-1** [comment]
@jeff-lim 좌표표현식은 동일해요, 다만 편집에 쓴 좌표자체가 동작하지 않는 것일 뿐...

@Yeyeon 한 가지 방법이 떠올랐어요, 이게 각 시/도마다 하나의 path로 구성되어있는데, 예연님이 편집하면 깨졌잖아요!? 제가 편집기로 열어보니 각 시/도가 하나의 개체로 묶여있더라구요, 그걸 따로 떼어내서 각각의 파일로 가져와서 줄이고 따로 저장해보시겠어요!?

**Comment by jeff-lim** [comment]
어도비 일러스터에서 svg 저장할때 버전이 다양하던데 버전같은거 바꾸면 가능하시 않을까요?
(참조 @Yeyeon https://github.com/Yeyeon)

2014년 8월 6일 오전 10:37, Seunghun Jang notifications@github.com님이 작성:

**Comment by Yeyeon** [comment]
@thechunsik 춘식님이 처음에 주신 지도파일도 일러스트레이터 프로그램에서 열어보면 각 시/도가 따로따로 패스가 있고 그게 맨 마지막에 그룹이 잡혀있더라고요! 저도 똑같이 시도별 패스 따로 잡고 맨 마지막에 전체를 그룹시켰어요. 그런데 왜인지... 원본은 작동되고 제가 그룹잡은건 안되는 이유가 이해가 안되지만.. 그럼 각 시/도별로 따로따로 떼어서 여러 개의 파일로 저장해보라는 말씀이신가욧?!

**Comment by hoony-o-1** [comment]
해결! [참조문서](http://blog.dokenzy.com/archives/1071)
