### ISSUE TITLE
금액 단위가 정확한가요?

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/wheredoesmymoneygo.kr#46]
연봉 3000만, 종합소득세 342만
일반, 지방 행정 1697원?? 단위가 맞는건가요?
각 주제별 금액을 더하면 종합소득세 나와야 되는거 아니에요?

http://www.wheredoesmymoneygo.kr/dailybread.html

혹시 아니라면 이유가 뭐죠? 설명이라도 있어야 될 듯..

**Comment by ytseo** [comment]
대충 밑에 있는 1,697 등등을 다 더하면 9,372원이 나오고 이 금액을 365로 곱하니깐 3,420,780원이 나오네요.

**Comment by mozodev** [comment]
아 하루 금액이라서 365를 곱하면 되는군요! 아무 생각없이 걍 보니까 단위가 안 맞아 보이네요... ㅎㅎ 역시 차분하심. 
그럼 종합소득세 (1년) 주제별 금액 (1일) 이런 식으로든 
뭔가 이렇게 1년을 내서 342만원을 내게 된거에요 이런 시각적이든 텍스트든 설명이 있으면 좋겠어요.
