### ISSUE TITLE
taxman.codenamu.org down!

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/wheredoesmymoneygo.kr#47]
http://taxman.codenamu.org/ko?callback=jQuery17106050002579577267_1435128427244&year=2013&indirects=true&income=30000000&_=1435128436101

@thechunsik 
우연히 들어가봤더니 우리의 택스맨이 또 내려갔더라고요...
https://github.com/codeforseoul/taxman
이 소스로 돌리면 되는거면 코드포서울 서버에서 돌릴까요? 계속 신경쓰기도 힘드실 듯 하고...

https://uptimerobot.com && https://ifttt.com && slack channel notification
이렇게 해서 슬랙 채널에다가 연결해놓으면 또 주저 앉으시면 우리가 알 수 있다는... ㅎㅎ

암튼 갑자기 든 생각 몇 자 적어봤습니다.

**Comment by hoony-o-1** [comment]
제가 서버를 자꾸 포맷하고 업데이트하고 해서 죽는것 같아요 ㅠ 코드포서울에 설치해두면 더 좋을 것 같긴 하네요!

**Comment by mozodev** [comment]
http://taxman.codenamu.org 
14.63.219.127 !!
